// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Artur Strazewicz

//! RDNA2 instruction families and the decoded opcode vocabulary.
//!
//! `Opcode` variant names match assembler mnemonics, so `@tagName` replaces the
//! opcode-to-string lookup table that a hand-written decoder normally carries as
//! a several-hundred-line switch.

/// Instruction encoding format.
pub const Family = enum {
    unknown,
    sop1,
    sop2,
    sopk,
    sopc,
    sopp,
    vop1,
    vop2,
    vop3,
    vop3p,
    vopc,
    vintrp,
    smem,
    mubuf,
    mtbuf,
    flat,
    ds,
    mimg,
    exp,

    pub fn name(self: Family) []const u8 {
        return switch (self) {
            .unknown => "unknown",
            inline else => |f| comptime up(@tagName(f)),
        };
    }

    /// sop1 -> "SOP1": family names are conventionally printed upper case.
    fn up(comptime s: []const u8) []const u8 {
        comptime var buf: [s.len]u8 = undefined;
        inline for (s, 0..) |c, i| {
            buf[i] = if (c >= 'a' and c <= 'z') c - ('a' - 'A') else c;
        }
        const frozen = buf;
        return &frozen;
    }
};

/// What an operand field actually encodes.
pub const OperandKind = enum {
    unknown,
    sgpr,
    vgpr,
    integer_inline_constant,
    float_inline_constant,
    literal_constant,
    vcc_lo,
    vcc_hi,
    vcc_z,
    exec_lo,
    exec_hi,
    exec_z,
    scc,
    m0,
    /// Trap temporary register (TTMP0..TTMP15 on GFX9+).
    ttmp,
    flat_scratch_base_lo,
    flat_scratch_base_hi,
    shared_base,
    shared_limit,
    private_base,
    private_limit,
    /// Per-lane LDS value selected by M0.
    lds_direct,
    /// Discarded destination / zero-valued source selector.
    null,
    pops_exiting_wave_id,
};

pub const ImageDimension = enum(u3) {
    dim_1d = 0,
    dim_2d = 1,
    dim_3d = 2,
    dim_2d_array = 3,
    dim_1d_array = 4,
    dim_2d_array_alt = 5,
    dim_2d_msaa = 6,
    dim_2d_msaa_array = 7,
};

pub const ImageSampleFlags = packed struct(u16) {
    lod: bool = false,
    bias: bool = false,
    derivative: bool = false,
    compare: bool = false,
    offset: bool = false,
    level_zero: bool = false,
    lod_clamp: bool = false,
    a16: bool = false,
    coherent_derivative: bool = false,
    gather_horizontal: bool = false,
    _reserved: u6 = 0,
};

/// Opcodes currently understood by the RDNA2 frontend.
pub const Opcode = enum {
    unknown,
    /// Recognized as belonging to a family, but not implemented.
    unsupported,

    // SOP1
    s_mov_b32,
    s_mov_b64,
    s_not_b32,
    s_not_b64,
    s_wqm_b64,
    s_brev_b32,
    s_bcnt1_i32_b32,
    s_bcnt1_i32_b64,
    s_ff1_i32_b32,
    s_flbit_i32_b64,
    s_bitset0_b32,
    s_bitset1_b32,
    s_getpc_b64,
    s_setpc_b64,
    s_and_saveexec_b32,
    s_and_saveexec_b64,
    s_orn2_saveexec_b64,
    s_andn1_saveexec_b32,
    s_andn1_saveexec_b64,
    s_abs_i32,
    s_bitreplicate_b64_b32,

    // SOP2
    s_add_u32,
    s_sub_u32,
    s_add_i32,
    s_sub_i32,
    s_addc_u32,
    s_subb_u32,
    s_min_i32,
    s_min_u32,
    s_max_i32,
    s_max_u32,
    s_cselect_b32,
    s_cselect_b64,
    s_and_b32,
    s_and_b64,
    s_or_b32,
    s_or_b64,
    s_xor_b32,
    s_xor_b64,
    s_andn2_b32,
    s_andn2_b64,
    s_orn2_b32,
    s_orn2_b64,
    s_nand_b32,
    s_nand_b64,
    s_nor_b32,
    s_nor_b64,
    s_xnor_b32,
    s_xnor_b64,
    s_lshl_b32,
    s_lshl_b64,
    s_lshr_b32,
    s_lshr_b64,
    s_ashr_i32,
    s_bfm_b32,
    s_bfm_b64,
    s_mul_i32,
    s_bfe_u32,
    s_bfe_u64,
    s_lshl1_add_u32,
    s_lshl2_add_u32,
    s_lshl3_add_u32,
    s_lshl4_add_u32,
    s_pack_ll_b32_b16,
    s_pack_lh_b32_b16,
    s_pack_hh_b32_b16,
    s_mul_hi_u32,

    // SOPC / SOPK
    s_cmp_eq_i32,
    s_cmp_lg_i32,
    s_cmp_gt_i32,
    s_cmp_ge_i32,
    s_cmp_lt_i32,
    s_cmp_le_i32,
    s_cmp_eq_u32,
    s_cmp_lg_u32,
    s_cmp_gt_u32,
    s_cmp_ge_u32,
    s_cmp_lt_u32,
    s_cmp_le_u32,
    s_cmp_lg_u64,
    s_bitcmp0_b32,
    s_bitcmp1_b32,
    s_movk_i32,
    s_mulk_i32,
    s_setreg_b32,
    s_waitcnt,

    // SOPP
    s_nop,
    s_endpgm,
    s_code_end,
    s_branch,
    s_cbranch_scc0,
    s_cbranch_scc1,
    s_cbranch_vccz,
    s_cbranch_vccnz,
    s_cbranch_execz,
    s_cbranch_execnz,
    s_barrier,
    s_sleep,
    s_sendmsg,
    s_ttrace_data,
    s_inst_prefetch,

    // SMEM
    s_load_dword,
    s_load_dwordx2,
    s_load_dwordx4,
    s_load_dwordx8,
    s_load_dwordx16,
    s_buffer_load_dword,
    s_buffer_load_dwordx2,
    s_buffer_load_dwordx4,
    s_buffer_load_dwordx8,
    s_buffer_load_dwordx16,

    // Vector ALU. Unknown encodings remain `.unsupported`; keeping the known
    // vocabulary here lets the IR and diagnostics avoid numeric opcode IDs.
    v_nop,
    v_mov_b32,
    v_readfirstlane_b32,
    v_readlane_b32,
    v_writelane_b32,
    v_cndmask_b32,
    v_cvt_f32_i32,
    v_cvt_f32_u32,
    v_cvt_u32_f32,
    v_cvt_i32_f32,
    v_cvt_f16_f32,
    v_cvt_f32_f16,
    v_cvt_f16_u16,
    v_cvt_f16_i16,
    v_cvt_u16_f16,
    v_cvt_i16_f16,
    v_cvt_rpi_i32_f32,
    v_cvt_flr_i32_f32,
    v_cvt_f32_ubyte0,
    v_cvt_f32_ubyte1,
    v_cvt_f32_ubyte2,
    v_cvt_f32_ubyte3,
    v_fract_f32,
    v_trunc_f32,
    v_ceil_f32,
    v_rndne_f32,
    v_floor_f32,
    v_exp_f32,
    v_log_f32,
    v_rcp_f32,
    v_rsq_f32,
    v_sqrt_f32,
    v_rcp_f16,
    v_rsq_f16,
    v_sqrt_f16,
    v_log_f16,
    v_exp_f16,
    v_floor_f16,
    v_ceil_f16,
    v_trunc_f16,
    v_rndne_f16,
    v_sin_f32,
    v_cos_f32,
    v_not_b32,
    v_bfrev_b32,
    v_ffbh_u32,
    v_ffbl_b32,
    v_add_f32,
    v_sub_f32,
    v_subrev_f32,
    v_mul_f32,
    v_mac_f32,
    v_madmk_f32,
    v_madak_f32,
    v_dot2c_f32_f16,
    v_mul_i32_i24,
    v_mul_u32_u24,
    v_min_f32,
    v_max_f32,
    v_min_i32,
    v_max_i32,
    v_min_u32,
    v_max_u32,
    v_lshr_b32,
    v_lshrrev_b32,
    v_ashr_i32,
    v_ashrrev_i32,
    v_lshl_b32,
    v_lshlrev_b32,
    v_and_b32,
    v_or_b32,
    v_xor_b32,
    v_xnor_b32,
    v_bcnt_u32_b32,
    v_mbcnt_lo_u32_b32,
    v_mbcnt_hi_u32_b32,
    v_add_nc_u32,
    v_addc_u32,
    v_sub_nc_u32,
    v_subrev_nc_u32,
    v_add_f16,
    v_sub_f16,
    v_subrev_f16,
    v_mul_f16,
    v_fmac_f16,
    v_fmamk_f16,
    v_fmaak_f16,
    v_max_f16,
    v_min_f16,
    v_mad_f32,
    v_fma_f32,
    v_cvt_pkrtz_f16_f32,
    v_bfe_u32,
    v_bfe_i32,
    v_bfi_b32,
    v_alignbit_b32,
    v_min3_f32,
    v_max3_f32,
    v_med3_f32,
    v_mul_lo_u32,
    v_mul_hi_u32,
    v_mul_lo_i32,
    v_mul_hi_i32,
    v_sad_u32,
    v_xad_u32,
    v_lshl_add_u32,
    v_add_lshl_u32,
    v_add3_u32,
    v_xor3_b32,
    v_or3_b32,
    v_and_or_b32,
    v_lshl_or_b32,
    v_pk_add_i16,
    v_pk_sub_i16,
    v_pk_add_u16,
    v_pk_sub_u16,
    v_pk_add_f16,
    v_pk_mul_f16,
    v_pk_fma_f16,
    v_mad_mixlo_f16,
    v_mad_mixhi_f16,

    // Vector compare and interpolation.
    v_cmp_f_f32,
    v_cmp_lt_f32,
    v_cmp_eq_f32,
    v_cmp_le_f32,
    v_cmp_gt_f32,
    v_cmp_lg_f32,
    v_cmp_ge_f32,
    v_cmp_o_f32,
    v_cmp_u_f32,
    v_cmp_nge_f32,
    v_cmp_nlg_f32,
    v_cmp_ngt_f32,
    v_cmp_nle_f32,
    v_cmp_neq_f32,
    v_cmp_nlt_f32,
    v_cmp_tru_f32,
    v_cmp_lt_i32,
    v_cmp_eq_i32,
    v_cmp_le_i32,
    v_cmp_gt_i32,
    v_cmp_ne_i32,
    v_cmp_ge_i32,
    v_cmp_lt_u32,
    v_cmp_eq_u32,
    v_cmp_le_u32,
    v_cmp_gt_u32,
    v_cmp_ne_u32,
    v_cmp_ge_u32,
    v_cmpx_lt_f32,
    v_cmpx_eq_f32,
    v_cmpx_le_f32,
    v_cmpx_gt_f32,
    v_cmpx_lg_f32,
    v_cmpx_ge_f32,
    v_cmpx_f_f32,
    v_cmpx_o_f32,
    v_cmpx_u_f32,
    v_cmpx_nge_f32,
    v_cmpx_nlg_f32,
    v_cmpx_ngt_f32,
    v_cmpx_nle_f32,
    v_cmpx_neq_f32,
    v_cmpx_nlt_f32,
    v_cmpx_tru_f32,
    v_cmpx_lt_i32,
    v_cmpx_eq_i32,
    v_cmpx_le_i32,
    v_cmpx_gt_i32,
    v_cmpx_ne_i32,
    v_cmpx_ge_i32,
    v_cmpx_lt_u32,
    v_cmpx_eq_u32,
    v_cmpx_le_u32,
    v_cmpx_gt_u32,
    v_cmpx_ne_u32,
    v_cmpx_ge_u32,
    v_interp_p1_f32,
    v_interp_p2_f32,
    v_interp_mov_f32,

    // Buffer, flat and data-share memory.
    buffer_load_format_x,
    buffer_load_format_xy,
    buffer_load_format_xyz,
    buffer_load_format_xyzw,
    buffer_store_format_x,
    buffer_store_format_xy,
    buffer_store_format_xyz,
    buffer_store_format_xyzw,
    buffer_load_ubyte,
    buffer_load_sbyte,
    buffer_load_ushort,
    buffer_load_sshort,
    buffer_load_dword,
    buffer_load_dwordx2,
    buffer_load_dwordx3,
    buffer_load_dwordx4,
    buffer_store_byte,
    buffer_store_short,
    buffer_store_dword,
    buffer_store_dwordx2,
    buffer_store_dwordx3,
    buffer_store_dwordx4,
    buffer_atomic_swap,
    buffer_atomic_add,
    buffer_atomic_sub,
    buffer_atomic_smin,
    buffer_atomic_umin,
    buffer_atomic_smax,
    buffer_atomic_umax,
    buffer_atomic_and,
    buffer_atomic_or,
    buffer_atomic_xor,
    tbuffer_load_format_x,
    tbuffer_load_format_xy,
    tbuffer_load_format_xyz,
    tbuffer_load_format_xyzw,
    tbuffer_store_format_x,
    tbuffer_store_format_xy,
    tbuffer_store_format_xyz,
    tbuffer_store_format_xyzw,
    flat_load_ubyte,
    flat_load_sbyte,
    flat_load_ushort,
    flat_load_sshort,
    flat_load_dword,
    flat_load_dwordx2,
    flat_load_dwordx3,
    flat_load_dwordx4,
    flat_store_byte,
    flat_store_short,
    flat_store_dword,
    flat_store_dwordx2,
    flat_store_dwordx3,
    flat_store_dwordx4,
    ds_add_u32,
    ds_sub_u32,
    ds_min_i32,
    ds_max_i32,
    ds_min_u32,
    ds_max_u32,
    ds_and_b32,
    ds_or_b32,
    ds_xor_b32,
    ds_write_b32,
    ds_write2_b32,
    ds_read_b32,
    ds_read2_b32,
    ds_read_b64,
    ds_read_b96,
    ds_read_b128,
    ds_write_b64,
    ds_write_b96,
    ds_write_b128,
    ds_read_ubyte,
    ds_read_sbyte,
    ds_read_ushort,
    ds_read_sshort,

    // Images and exports.
    image_load,
    image_load_mip,
    image_store,
    image_store_mip,
    image_get_resinfo,
    image_get_lod,
    image_atomic_add,
    image_atomic_umin,
    image_atomic_umax,
    image_atomic_and,
    image_atomic_or,
    image_atomic_xor,
    image_sample,
    image_gather4,
    exp,

    /// Assembler mnemonic. Identical to the variant name, so no table is needed.
    pub fn mnemonic(self: Opcode) []const u8 {
        return @tagName(self);
    }

    /// Control-transfer instructions, used to collect branch targets.
    pub fn isBranch(self: Opcode) bool {
        return switch (self) {
            .s_branch,
            .s_cbranch_scc0,
            .s_cbranch_scc1,
            .s_cbranch_vccz,
            .s_cbranch_vccnz,
            .s_cbranch_execz,
            .s_cbranch_execnz,
            => true,
            else => false,
        };
    }

    /// Shader termination opcodes. GFX10 export shaders commonly use
    /// `s_code_end` before their embedded metadata instead of `s_endpgm`.
    pub fn isProgramEnd(self: Opcode) bool {
        return self == .s_endpgm or self == .s_code_end;
    }
};

test "mnemonic is derived from the variant name" {
    const std = @import("std");
    try std.testing.expectEqualStrings("s_mov_b32", Opcode.s_mov_b32.mnemonic());
    try std.testing.expectEqualStrings("s_bitreplicate_b64_b32", Opcode.s_bitreplicate_b64_b32.mnemonic());
    try std.testing.expectEqualStrings("s_cbranch_execnz", Opcode.s_cbranch_execnz.mnemonic());
}

test "family names print upper case" {
    const std = @import("std");
    try std.testing.expectEqualStrings("SOP1", Family.sop1.name());
    try std.testing.expectEqualStrings("SOPP", Family.sopp.name());
    try std.testing.expectEqualStrings("SMEM", Family.smem.name());
    try std.testing.expectEqualStrings("unknown", Family.unknown.name());
}

test "branches are recognized" {
    const std = @import("std");
    try std.testing.expect(Opcode.s_branch.isBranch());
    try std.testing.expect(Opcode.s_cbranch_vccz.isBranch());
    try std.testing.expect(!Opcode.s_endpgm.isBranch());
    try std.testing.expect(!Opcode.s_mov_b32.isBranch());
    try std.testing.expect(Opcode.s_endpgm.isProgramEnd());
    try std.testing.expect(Opcode.s_code_end.isProgramEnd());
}
